version: "3.9"

services:
  kyureeus-alleye-web:
    build: .
    container_name: kyureeus-alleye
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount your custom Nginx config
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount SSL certs (Let's Encrypt or self-signed)
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - lms-net
networks:
  lms-net:
    driver: bridge

